# Generated by Django 3.2.15 on 2022-10-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
