# Generated by Django 3.2.15 on 2022-10-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20221025_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
