# Generated by Django 3.2.15 on 2022-10-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_userprofile_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
