# Generated by Django 3.2.15 on 2022-10-28 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_auto_20221028_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 22, 19, 54, 201051, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
