# Generated by Django 3.2.15 on 2022-10-31 20:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_auto_20221031_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends2',
            field=models.ManyToManyField(blank=True, to='social.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 20, 45, 11, 537313, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Friend_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='social.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='social.userprofile')),
            ],
        ),
    ]
