# Generated by Django 3.2.15 on 2022-10-31 21:03

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0036_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 21, 3, 52, 680771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends2',
            field=models.ManyToManyField(blank=True, related_name='friends2', to=settings.AUTH_USER_MODEL),
        ),
    ]
