# Generated by Django 3.2.15 on 2022-10-31 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0037_auto_20221031_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 21, 8, 14, 948311, tzinfo=utc)),
        ),
    ]
