# Generated by Django 3.2.15 on 2022-11-01 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0039_alter_post_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends2',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 16, 59, 58, 992276, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
