# Generated by Django 3.2.15 on 2022-11-03 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0043_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 21, 27, 32, 648247, tzinfo=utc)),
        ),
    ]
