# Generated by Django 3.2.15 on 2022-10-28 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_auto_20221028_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 21, 15, 24, 376545, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
