# Generated by Django 3.2.15 on 2022-10-31 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20221028_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 0, 20, 59, 701486, tzinfo=utc)),
        ),
    ]
