# Generated by Django 3.2.15 on 2022-10-31 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0027_auto_20221031_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 19, 35, 15, 345061, tzinfo=utc)),
        ),
    ]
