# Generated by Django 3.2.15 on 2022-11-01 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0040_auto_20221101_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 17, 16, 7, 363597, tzinfo=utc)),
        ),
    ]
